site_name: Goldilocks Documentation
site_url: https://stfc.github.io/goldilocks/
use_directory_urls: false
docs_dir: docs

theme:
  name: material
  palette:
    scheme: default  # or slate, dracula, etc.
    primary: grey  # main color
    accent: amber     # highlights and links
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: 
      - Data input page: intro.md
      - Deterministic generation: deterministic.md
      - LLM generation: chat_llm.md
  - Development:
      - For developers: for-developers.md
  - Data:
      - Data availiability: data-availiability.md
  - License: license.md


